export type Badge = "live" | "new" | "hot";

export const categories = [
  "All",
  "Cardio",
  "Strength",
  "Recovery",
  "Nutrition",
  "Mindfulness",
  "Sleep",
  "Longevity",
  "Gut Health",
  "Hydration",
  "Fasting",
  "Anti-Inflammatory",
  "Heart Health",
  "Brain Health",
  "Immunity",
  "Hormone Balance",
  "Skin Health",
  "Bone Health",
  "Metabolism",
  "Weight Management",
  "Stress Relief",
  "Breathwork",
  "Yoga",
  "Mobility",
  "Supplements",
  "Superfoods",
  "Plant-Based",
  "Protein",
  "Antioxidants",
  "Detox",
  "Cold Therapy",
  "Sauna & Heat",
  "Blue Zones",
  "Circadian Health",
  "Meditation",
] as const;

export type Category = (typeof categories)[number];
